<?php

namespace FootstatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChampionnatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionnatRepository extends EntityRepository
{
}
