<?php

namespace FootstatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EquipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipesRepository extends EntityRepository
{
    public function byChampionnat($championnat){
        $db = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.championnat = :championnat')
                ->orderBy('u.id')
                ->setParameter('championnat', $championnat);
        return $db->getQuery()->getResult();
                
    }
    
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
                ->Select('u')
                ->Where('u.id IN (:array)')
                ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
}
