<?php

namespace FootstatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MatchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchesRepository extends EntityRepository
{
    public function byChampionnat($championnat){
        $db = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.championnat = :championnat')
                ->orderBy('u.id')
                ->setParameter('championnat', $championnat)
                ->orderBy('u.date', 'ASC')
                ->setMaxResults(10);
        return $db->getQuery()->getResult();
                
    }
}
