<?php

namespace FootstatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MatchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchesRepository extends EntityRepository
{
    public function byChampionnat($championnat){
        $db = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.championnat = :championnat')
                ->orderBy('u.id')
                ->setParameter('championnat', $championnat)
                ->orderBy('u.date', 'ASC')
                ->setMaxResults(10);
        return $db->getQuery()->getResult();                
    }
    
    public function byDate($date){
        $db = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.date = :date')
                
                ->setParameter('date', $date." %");
        return $db->getQuery()->getResult();
                
    }
   
    public function byNextmatchs($equipe){
        $now = date('Y-m-d').' 00:00:00';
        $db = $this->createQueryBuilder('u')
                ->select('u')
                ->andWhere('u.equipeDom = :equipe')
                ->orWhere('u.equipeExt = :equipe')
                ->andWhere('u.date >= :now' )
                ->andWhere('u.type = 1')
                ->orderBy('u.date')
                ->setParameter('equipe', $equipe)
                ->setParameter('now', $now);
        return $db->getQuery()->getResult();
                
    }
    
     public function byNextmChamp($championnat){
        $now = date('Y-m-d').' 00:00:00';
        $db = $this->createQueryBuilder('u')
                ->select('u')
                ->andWhere('u.championnat = :championnat')
                ->andWhere('u.date >= :now' )
                ->andWhere('u.type = 1')
                ->orderBy('u.date')
                ->setParameter('championnat', $championnat)
                ->setParameter('now', $now)
                ->setMaxResults( 15 );
        return $db->getQuery()->getResult();
                
    }
}
