
Acceuil:
    path:     /
    defaults: { _controller: FootstatBundle:Matches:TodayMatches }
    
Championnats:
    path:     /championnats
    defaults: { _controller: FootstatBundle:Championnats:Championnats }


AllEquipesChampionnat:
    path:     /equipes/add/{id}
    defaults: { _controller: FootstatBundle:EquipesAdmin:Getallequipes }

ChampionnatEquipes:
    path:     /championnats/{championnat}
    defaults: { _controller: FootstatBundle:Equipes:Championnat }
    
EquipePresentation:
    path:     /equipes/{equipe}
    defaults: { _controller: FootstatBundle:Equipes:Equipe }
       
Favoris:
    path:     /favoris
    defaults: { _controller: FootstatBundle:Favoris:Favoris }

AjouterFavoris:
    path:     /favorisajouter/{id}
    defaults: { _controller: FootstatBundle:Favoris:Ajouter }

SupprimerFavoris:
    path:     /supprimer-favoris/{id}
    defaults: { _controller: FootstatBundle:Favoris:Supprimer }
    
AllmatchEquipe:
    path:     /matches/{equipe}
    defaults: { _controller: FootstatBundle:Equipes:Allmatch }
    
DataEquipes:
    path:     /stat/{matchid}
    defaults: { _controller: FootstatBundle:Matches:Matche }

AjouterMesEquipes:
    path:     /addequipe/{id}
    defaults: { _controller: UtilisateursBundle:Utilisateurs:Addequipe }
    options:
        expose: true
SuprrimerMesEquipes:
    path:     /removeequipe/{id}
    defaults: { _controller: UtilisateursBundle:Utilisateurs:Removeequipe }
    options:
        expose: true
    
MesEquipesFavoris:
    path:     /me/equipes
    defaults: { _controller: UtilisateursBundle:Utilisateurs:Favoris }

AddCombine:
    path:     /combine/add/{idmatch}
    defaults: { _controller: FootstatBundle:Parie:Combine }
    options:
        expose: true

AddParie:
    path:     /Parie/add/{idmatch}
    defaults: { _controller: FootstatBundle:Parie:Addparie }
    options:
        expose: true

RemoveopenCombine:
    path:     /opencombine/delete
    defaults: { _controller: FootstatBundle:Parie:Removeopencmb }
    options:
        expose: true